#! /usr/bin/env perl
# ABSTRACT: convert birthday csv to LyX document
# PODNAME: birthday2lyx

use strict;
use warnings;

use FindBin qw($Bin);
use lib "$Bin/../lib/perl5";

use App::BirthdayToLyx;

my $app = App::BirthdayToLyx->new();
$app->process_args(@ARGV);
exit( $app->run ? 0 : 1 );

